[tool.poetry]
name = "grover"
version = "0.1.0"
description = "Grover"
authors = ["Tencent AILab", "Ankur Kumar <ank@leoank.me>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
